apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  labels:
    app: go-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-k8s
  template:
    metadata:
      labels:
        app: go-k8s
    spec:
      containers:
      - name: go-k8s-server
        image: matheusjustino/go-k8s:v2
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: 60Mi
            cpu: 500m
          requests:
            memory: 40Mi
            cpu: 250m
