apiVersion: v1
kind: Service
metadata:
  name: go-server
spec:
  selector:
    app: go-k8s
  ports:
    - protocol: TCP
      name: http-svc
      port: 3000
      targetPort: 3000
  type: LoadBalancer